a=55;
b=65;
echo "Sum of $a and $b";
echo "-----------------";
c=$((a+b));
echo $c;
echo "Subtraction of $a and $b";
echo "-------------------------";
d=$((a-b));
echo $d;
echo "Division of $a and $b";
echo "----------------------";
e=$((a/b));
echo $e;
echo "Multiplication of $a and $b";
echo "---------------------------";
f=$((a*b));
echo $f;
